baseURL = "https://gillandsiphon.github.io/"
languageCode = "en-us"
title = "ğŸŒ Gill and Siphon"
theme = "PaperMod"
include = "img"

[params]
    ShowToc= true
  [params.homeInfoParams]
    Title = "Posts"
